import re
import sys

regex = "K[KR]CGH[LMQR]"
string = "MSHMDAEDAQFQKEVAEVKQWWNDSRWRYTKRTFTAEEIVSKRGNLKITYPSNSQSKKLWNIVEHRFKNKDVSYTYGCLDPVMVTQMAKYLDTVYVSGWQASSTASSTDEPGPDLADYPYTTVPNKVGHLFMAQLFHDRKQREERLTTPKADRAKVANVDYLRPIIADADTGHGGLTAIMKLTKLFIEKGAAGIHIEDQAPGTKKCGHMAGKVLVPISEHINRLVAIRAQADIMGTDLLAVARTDSEAATLITSTIDPRDHYYIQGCTNPALQPLSELMYAAEQSGKSGSELQAIEDAWVKEANLKLFHEAVVDTINAGVHVNKQELINQFLEQSKGKSNAEARTIAQGLTGVDVYFNWDAARTREGYYRYKGGCQCAINRAIAYAPFCDMIWMESKLPDYAQAKEFADGVHAVWPEQKLAYNLSPSFNWKAAMPRDEQETYIQRLAQLGYCWQFITLAGLHQSALMADTFSKAYSKQGMRAYGEIIQEPEAENKVDVLTHQKWSGANYVDNMLKMVSGGVSSTAAMGKGVTEDQFK"
FASTA_ID = "gb|AAM89498|537aa"
PROSITE_ID = "PS00161"

mathes = re.search(regex, string )
active_site = mathes.group(0)
print(active_site)
start = mathes.start()
print(mathes.end())

print("Isocitrate lyase " + FASTA_ID + " contains its active site " +
      PROSITE_ID + " starting from " + repr(start) +"th" + " position")